module.exports = {"London Stansted":"STN",
"Aarhus":"AAR",
"Agadir":"AGA",
"Alghero":"AHO",
"Alicante":"ALC",
"Almeria":"LEI",
"Ancona":"AOI",
"Athens":"ATH",
"Baden-Baden":"FKB",
"Barcelona El Prat":"BCN",
"Bari":"BRI",
"Basel":"BSL",
"Bergerac":"EGC",
"Berlin Schonefeld":"SXF",
"Beziers":"BZR",
"Biarritz":"BIQ",
"Billund":"BLL",
"Birmingham":"BHX",
"Bologna":"BLQ",
"Bordeaux":"BOD",
"Bournemouth":"BOH",
"Bratislava":"BTS",
"Bremen":"BRE",
"Brest":"BES",
"Brindisi":"BDS",
"Bristol":"BRS",
"Brive":"BVE",
"Brno":"BRQ",
"Brussels Charleroi":"CRL",
"Brussels Zaventem":"BRU",
"Bucharest (Otopeni)":"OTP",
"Budapest":"BUD",
"Bydgoszcz":"BZG",
"Cagliari":"CAG",
"Carcassonne":"CCF",
"Cardiff":"CWL",
"Catania":"CTA",
"Chania":"CHQ",
"Clermont Ferrand":"CFE",
"Cologne":"CGN",
"Comiso":"CIY",
"Copenhagen":"CPH",
"Corfu":"CFU",
"Cork":"ORK",
"Crotone":"CRV",
"Cuneo":"CUF",
"Deauville":"DOL",
"Derry":"LDY",
"Dinard":"DNR",
"Dole":"DLE",
"Dortmund":"DTM",
"Dublin":"DUB",
"Dusseldorf Weeze":"NRN",
"East Midlands":"EMA",
"Edinburgh":"EDI",
"Eindhoven":"EIN",
"Essaouira":"ESU",
"Faro":"FAO",
"Fez":"FEZ",
"Figari":"FSC",
"Frankfurt Hahn":"HHN",
"Fuerteventura":"FUE",
"Gdansk":"GDN",
"Genoa":"GOA",
"Girona Barcelona":"GRO",
"Glasgow International":"GLA",
"Glasgow Prestwick":"PIK",
"Gothenburg City":"GSE",
"Gothenburg Landvetter":"GOT",
"Gran Canaria":"LPA",
"Grenoble":"GNB",
"Hamburg":"HAM",
"Haugesund":"HAU",
"Ibiza":"IBZ",
"Jerez":"XRY",
"Kalamata":"KLX",
"Katowice":"KTW",
"Kaunas":"KUN",
"Kefalonia":"EFL",
"Kerry":"KIR",
"Knock Ireland West":"NOC",
"Kos":"KGS",
"Krakow":"KRK",
"Lamezia":"SUF",
"Lanzarote":"ACE",
"Lappeenranta":"LPP",
"La Rochelle":"LRH",
"Leeds Bradford":"LBA",
"Leipzig":"LEJ",
"Lille":"LIL",
"Limoges":"LIG",
"Linz":"LNZ",
"Lisbon":"LIS",
"Liverpool":"LPL",
"Lodz":"LCJ",
"London Gatwick":"LGW",
"London Luton":"LTN",
"Lorient":"LRT",
"Lourdes":"LDE",
"Lublin":"LUZ",
"Maastricht":"MST",
"Madrid":"MAD",
"Malaga":"AGP",
"Malmo":"MMX",
"Malta":"MLA",
"Manchester":"MAN",
"Marrakesh":"RAK",
"Marseille Provence":"MRS",
"Memmingen (Munich West)":"FMM",
"Menorca":"MAH",
"Milan Bergamo":"BGY",
"Montpellier":"MPL",
"Münster":"FMO",
"Murcia":"MJV",
"Nador":"NDR",
"Nantes":"NTE",
"Newcastle":"NCL",
"Nice":"NCE",
"Nimes":"FNI",
"Nuremberg":"NUE",
"Osijek":"OSI",
"Oslo Rygge":"RYG",
"Oslo Torp":"TRF",
"Ostrava":"OSR",
"Oujda":"OUD",
"Palermo":"PMO",
"Palma":"PMI",
"Paphos":"PFO",
"Paris Beauvais":"BVA",
"Paris Vatry":"XCR",
"Parma":"PMF",
"Patras (Araxos)":"GPA",
"Perpignan":"PGF",
"Perugia":"PEG",
"Pescara":"PSR",
"Pisa":"PSA",
"Plovdiv":"PDV",
"Podgorica":"TGD",
"Poitiers":"PIS",
"Ponta Delgada":"PDL",
"Porto":"OPO",
"Poznan":"POZ",
"Prague":"PRG",
"Pula":"PUY",
"Rabat":"RBA",
"Rennes":"RNS",
"Reus Barcelona":"REU",
"Rhodes":"RHO",
"Riga":"RIX",
"Rijeka":"RJK",
"Rodez":"RDZ",
"Rome Ciampino":"CIA",
"Rome Fiumicino":"FCO",
"Rzeszow":"RZE",
"Salzburg":"SZG",
"Santander":"SDR",
"Santiago":"SCQ",
"Seville":"SVQ",
"Shannon":"SNN",
"Skelleftea":"SFT",
"St Etienne":"EBU",
"Stockholm Skavsta":"NYO",
"Stockholm Vasteras":"VST",
"Strasbourg":"SXB",
"Szczecin":"SZZ",
"Tallinn":"TLL",
"Tampere":"TMP",
"Tangier":"TNG",
"Tenerife North":"TFN",
"Tenerife Sth":"TFS",
"Thessaloniki":"SKG",
"Toulon":"TLN",
"Tours":"TUF",
"Trapani":"TPS",
"Trieste":"TRS",
"Turin":"TRN",
"Valencia":"VLC",
"Valladolid":"VLL",
"Växjö":"VXO",
"Venice Treviso":"TSF",
"Vilnius":"VNO",
"Warsaw Modlin":"WMI",
"Wroclaw":"WRO",
"Zadar":"ZAD",
"Zakynthos":"ZTH",
"Zaragoza":"ZAZ"}